### ISSUE TITLE
Implementing a RESTful route with multiple HTTP methods

### ISSUE THREAD

**Issue by tejkweku** [Lablnet/ZestRouter#1]
I need to implement a RESTful route which has multiple HTTP methods associated with it. For instance: 
```
GET /members -  return a list of members
POST /members - save member information provided
```
What happens is that the last HTTP method implemented is that used. The rest, first to last but one, return a blank page with no 404 or error neither returned nor logged.

**Comment by lablnet** [comment]
Zest Router already support rests routes

Consider the following example

```php
$router->get('members', function () {
    //Show all members
});


$router->post('members', function () {
    //Save member information
});
```
Instead of using closure function you may also provide controller like 

```php
$router->get('members','Members@all');
```
here it calls `all` method of `Members` class
Default location of `Controllers` is `App\Controllers` you may change by providing `namespace`

```php
$router->get('members','Members@al@Users\Controllers');
```
Now load class from `Users\Controllers`

### Controllers structure
```php
<?php
namespace App\Controllers;

class Members
{
    /**
     * Show the member page.
     *
     * @return void
     */
    public function all()
    {
        //Fetch all members and printOut
    }
}
```
Here `namespace` refer to `directory` if your`Controller` is in `Users` so namespace much be

```php
namespace Users\Controllers;
```

Thanks

**Comment by tejkweku** [comment]
Thanks for the clarification.
